"""describe your changes

Revision ID: 168653f08fea
Revises: a94a4a27d018
Create Date: 2026-07-08 23:50:00.261254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168653f08fea'
down_revision = 'a94a4a27d018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.alter_column('is_marriage',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.alter_column('is_marriage',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
