"""add tow field , religin to soldiers table

Revision ID: 5e8f6afdb889
Revises: a9048af43d52
Create Date: 2026-07-18 15:13:05.341552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8f6afdb889'
down_revision = 'a9048af43d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.drop_column('religion')
        batch_op.drop_column('field')

    # ### end Alembic commands ###
