"""Add excel_file column to courses

Revision ID: a94a4a27d018
Revises: c3747b30f97b
Create Date: 2026-07-08 20:05:35.892284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94a4a27d018'
down_revision = 'c3747b30f97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excel_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('excel_file')

    # ### end Alembic commands ###
