"""add location and organaiztion to soldiers table

Revision ID: c3747b30f97b
Revises: 
Create Date: 2026-07-08 16:20:17.828453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3747b30f97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_marriage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('battalion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_green', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True, erver_default=sa.text('CURRENT_TIMESTAMP')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soldiers', schema=None) as batch_op:
        batch_op.drop_column('create_at')
        batch_op.drop_column('is_green')
        batch_op.drop_column('status')
        batch_op.drop_column('company')
        batch_op.drop_column('battalion')
        batch_op.drop_column('is_marriage')
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
