"""add created_by to User model

Revision ID: d8abc7ad77d5
Revises: 0d355ea98b71
Create Date: 2026-08-10 18:17:55.461671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8abc7ad77d5'
down_revision = '0d355ea98b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_users_created_by', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_created_by'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_created_by', 'users', ['fk_users_created_by'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_created_by'), 'users', ['created_by'], ['id'])
        batch_op.drop_column('fk_users_created_by')

    # ### end Alembic commands ###
